package com.utopiannerd.netflix.titles.analytics.model;

import com.google.common.base.MoreObjects;
import java.util.Objects;

public final class NetflixTitle {

  private final String showId;
  private final String type;
  private final String title;
  private final String director;
  private final String cast;
  private final String country;
  private final String dateAdded;
  private final String releaseYear;
  private final String rating;
  private final String duration;
  private final String listedIn;
  private final String description;

  // region Constructor, getters, equals, hashCode, toString, builder -- generated by BoB the
  // Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here:
  // https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  private NetflixTitle(
      String showId,
      String type,
      String title,
      String director,
      String cast,
      String country,
      String dateAdded,
      String releaseYear,
      String rating,
      String duration,
      String listedIn,
      String description) {
    this.showId = Objects.requireNonNull(showId);
    this.type = Objects.requireNonNull(type);
    this.title = Objects.requireNonNull(title);
    this.director = Objects.requireNonNull(director);
    this.cast = Objects.requireNonNull(cast);
    this.country = Objects.requireNonNull(country);
    this.dateAdded = Objects.requireNonNull(dateAdded);
    this.releaseYear = Objects.requireNonNull(releaseYear);
    this.rating = Objects.requireNonNull(rating);
    this.duration = Objects.requireNonNull(duration);
    this.listedIn = Objects.requireNonNull(listedIn);
    this.description = Objects.requireNonNull(description);
  }

  // region Getters -- generated by BoB the Builder of Beans
  public String getShowId() {
    return showId;
  }

  public String getType() {
    return type;
  }

  public String getTitle() {
    return title;
  }

  public String getDirector() {
    return director;
  }

  public String getCast() {
    return cast;
  }

  public String getCountry() {
    return country;
  }

  public String getDateAdded() {
    return dateAdded;
  }

  public String getReleaseYear() {
    return releaseYear;
  }

  public String getRating() {
    return rating;
  }

  public String getDuration() {
    return duration;
  }

  public String getListedIn() {
    return listedIn;
  }

  public String getDescription() {
    return description;
  } // endregion Getters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    NetflixTitle that = (NetflixTitle) o;

    return Objects.equals(this.getShowId(), that.getShowId())
        && Objects.equals(this.getType(), that.getType())
        && Objects.equals(this.getTitle(), that.getTitle())
        && Objects.equals(this.getDirector(), that.getDirector())
        && Objects.equals(this.getCast(), that.getCast())
        && Objects.equals(this.getCountry(), that.getCountry())
        && Objects.equals(this.getDateAdded(), that.getDateAdded())
        && Objects.equals(this.getReleaseYear(), that.getReleaseYear())
        && Objects.equals(this.getRating(), that.getRating())
        && Objects.equals(this.getDuration(), that.getDuration())
        && Objects.equals(this.getListedIn(), that.getListedIn())
        && Objects.equals(this.getDescription(), that.getDescription());
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        getShowId(),
        getType(),
        getTitle(),
        getDirector(),
        getCast(),
        getCountry(),
        getDateAdded(),
        getReleaseYear(),
        getRating(),
        getDuration(),
        getListedIn(),
        getDescription());
  } // endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
        .add("showId", getShowId())
        .add("type", getType())
        .add("title", getTitle())
        .add("director", getDirector())
        .add("cast", getCast())
        .add("country", getCountry())
        .add("dateAdded", getDateAdded())
        .add("releaseYear", getReleaseYear())
        .add("rating", getRating())
        .add("duration", getDuration())
        .add("listedIn", getListedIn())
        .add("description", getDescription())
        .toString();
  } // endregion toString()

  // region Builder -- generated by BoB the Builder of Beans
  public static NetflixTitle.Builder builder() {
    return new NetflixTitle.Builder();
  }

  public static NetflixTitle.Builder builder(NetflixTitle data) {
    return new NetflixTitle.Builder(data);
  }

  public static final class Builder {

    private String showId;
    private String type;
    private String title;
    private String director;
    private String cast;
    private String country;
    private String dateAdded;
    private String releaseYear;
    private String rating;
    private String duration;
    private String listedIn;
    private String description;

    private Builder() {}

    private Builder(NetflixTitle initialData) {
      this.showId = initialData.showId;
      this.type = initialData.type;
      this.title = initialData.title;
      this.director = initialData.director;
      this.cast = initialData.cast;
      this.country = initialData.country;
      this.dateAdded = initialData.dateAdded;
      this.releaseYear = initialData.releaseYear;
      this.rating = initialData.rating;
      this.duration = initialData.duration;
      this.listedIn = initialData.listedIn;
      this.description = initialData.description;
    }

    public Builder setShowId(String showId) {
      this.showId = showId;
      return this;
    }

    public Builder setType(String type) {
      this.type = type;
      return this;
    }

    public Builder setTitle(String title) {
      this.title = title;
      return this;
    }

    public Builder setDirector(String director) {
      this.director = director;
      return this;
    }

    public Builder setCast(String cast) {
      this.cast = cast;
      return this;
    }

    public Builder setCountry(String country) {
      this.country = country;
      return this;
    }

    public Builder setDateAdded(String dateAdded) {
      this.dateAdded = dateAdded;
      return this;
    }

    public Builder setReleaseYear(String releaseYear) {
      this.releaseYear = releaseYear;
      return this;
    }

    public Builder setRating(String rating) {
      this.rating = rating;
      return this;
    }

    public Builder setDuration(String duration) {
      this.duration = duration;
      return this;
    }

    public Builder setListedIn(String listedIn) {
      this.listedIn = listedIn;
      return this;
    }

    public Builder setDescription(String description) {
      this.description = description;
      return this;
    }

    public NetflixTitle build() {
      return new NetflixTitle(
          showId,
          type,
          title,
          director,
          cast,
          country,
          dateAdded,
          releaseYear,
          rating,
          duration,
          listedIn,
          description);
    }
  } // endregion Builder
  // endregion Constructor, getters, equals, hashCode, toString, builder
}
