/* (C)2023 */
package com.utopiannerd.techcoaching.dao.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import java.sql.Date;
import java.util.Objects;
import java.util.StringJoiner;

@Entity
public class Batch {

  @Id private long batchId;
  private long courseId;
  private Date batchStartDate;
  private Date batchEndDate;
  private int totalSeatsCapacity;
  private int totalSeatsAvailable;

  // region Constructor, getters, setters, equals, hashCode, toString, builder -- generated by BoB
  // the Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here:
  // https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  protected Batch(
      long batchId,
      long courseId,
      Date batchStartDate,
      Date batchEndDate,
      int totalSeatsCapacity,
      int totalSeatsAvailable) {
    this.batchId = batchId;
    this.courseId = courseId;
    this.batchStartDate = Objects.requireNonNull(batchStartDate);
    this.batchEndDate = Objects.requireNonNull(batchEndDate);
    this.totalSeatsCapacity = totalSeatsCapacity;
    this.totalSeatsAvailable = totalSeatsAvailable;
  }

  public Batch() {}

  // region Getters and setters -- generated by BoB the Builder of Beans
  public long getBatchId() {
    return batchId;
  }

  public void setBatchId(long batchId) {
    this.batchId = batchId;
  }

  public long getCourseId() {
    return courseId;
  }

  public void setCourseId(long courseId) {
    this.courseId = courseId;
  }

  public Date getBatchStartDate() {
    return batchStartDate;
  }

  public void setBatchStartDate(Date batchStartDate) {
    this.batchStartDate = Objects.requireNonNull(batchStartDate);
  }

  public Date getBatchEndDate() {
    return batchEndDate;
  }

  public void setBatchEndDate(Date batchEndDate) {
    this.batchEndDate = Objects.requireNonNull(batchEndDate);
  }

  public int getTotalSeatsCapacity() {
    return totalSeatsCapacity;
  }

  public void setTotalSeatsCapacity(int totalSeatsCapacity) {
    this.totalSeatsCapacity = totalSeatsCapacity;
  }

  public int getTotalSeatsAvailable() {
    return totalSeatsAvailable;
  }

  public void setTotalSeatsAvailable(int totalSeatsAvailable) {
    this.totalSeatsAvailable = totalSeatsAvailable;
  } // endregion Getters and setters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    Batch that = (Batch) o;

    return Objects.equals(this.getBatchId(), that.getBatchId())
        && Objects.equals(this.getCourseId(), that.getCourseId())
        && Objects.equals(this.getBatchStartDate(), that.getBatchStartDate())
        && Objects.equals(this.getBatchEndDate(), that.getBatchEndDate())
        && Objects.equals(this.getTotalSeatsCapacity(), that.getTotalSeatsCapacity())
        && Objects.equals(this.getTotalSeatsAvailable(), that.getTotalSeatsAvailable());
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        getBatchId(),
        getCourseId(),
        getBatchStartDate(),
        getBatchEndDate(),
        getTotalSeatsCapacity(),
        getTotalSeatsAvailable());
  } // endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
        .add("batchId=" + getBatchId())
        .add("courseId=" + getCourseId())
        .add("batchStartDate=" + getBatchStartDate())
        .add("batchEndDate=" + getBatchEndDate())
        .add("totalSeatsCapacity=" + getTotalSeatsCapacity())
        .add("totalSeatsAvailable=" + getTotalSeatsAvailable())
        .toString();
  } // endregion toString()

  // region Builder -- generated by BoB the Builder of Beans
  public static Batch.Builder builder() {
    return new Batch.Builder();
  }

  public static Batch.Builder builder(Batch data) {
    return new Batch.Builder(data);
  }

  public static final class Builder {

    private long batchId;
    private long courseId;
    private Date batchStartDate;
    private Date batchEndDate;
    private int totalSeatsCapacity;
    private int totalSeatsAvailable;

    private Builder() {}

    private Builder(Batch initialData) {
      this.batchId = initialData.batchId;
      this.courseId = initialData.courseId;
      this.batchStartDate = initialData.batchStartDate;
      this.batchEndDate = initialData.batchEndDate;
      this.totalSeatsCapacity = initialData.totalSeatsCapacity;
      this.totalSeatsAvailable = initialData.totalSeatsAvailable;
    }

    public Builder setBatchId(long batchId) {
      this.batchId = batchId;
      return this;
    }

    public Builder setCourseId(long courseId) {
      this.courseId = courseId;
      return this;
    }

    public Builder setBatchStartDate(Date batchStartDate) {
      this.batchStartDate = batchStartDate;
      return this;
    }

    public Builder setBatchEndDate(Date batchEndDate) {
      this.batchEndDate = batchEndDate;
      return this;
    }

    public Builder setTotalSeatsCapacity(int totalSeatsCapacity) {
      this.totalSeatsCapacity = totalSeatsCapacity;
      return this;
    }

    public Builder setTotalSeatsAvailable(int totalSeatsAvailable) {
      this.totalSeatsAvailable = totalSeatsAvailable;
      return this;
    }

    public Batch build() {
      return new Batch(
          batchId, courseId, batchStartDate, batchEndDate, totalSeatsCapacity, totalSeatsAvailable);
    }
  } // endregion Builder
  // endregion Constructor, getters, setters, equals, hashCode, toString, builder
}
