/* (C)2023 */
package com.utopiannerd.techcoaching.dao.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import java.util.Objects;
import java.util.StringJoiner;

@Entity
public class Course {

  @Id private long courseId;
  private String courseName;
  private boolean isActive;

  // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the
  // Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here:
  // https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  public Course(long courseId, String courseName, boolean isActive) {
    this.courseId = courseId;
    this.courseName = Objects.requireNonNull(courseName);
    this.isActive = isActive;
  }

  public Course() {}

  // region Getters and setters -- generated by BoB the Builder of Beans
  public long getCourseId() {
    return courseId;
  }

  public void setCourseId(long courseId) {
    this.courseId = courseId;
  }

  public String getCourseName() {
    return courseName;
  }

  public void setCourseName(String courseName) {
    this.courseName = Objects.requireNonNull(courseName);
  }

  public boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  } // endregion Getters and setters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    Course that = (Course) o;

    return Objects.equals(this.getCourseId(), that.getCourseId())
        && Objects.equals(this.getCourseName(), that.getCourseName())
        && Objects.equals(this.getIsActive(), that.getIsActive());
  }

  @Override
  public int hashCode() {
    return Objects.hash(getCourseId(), getCourseName(), getIsActive());
  } // endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
        .add("courseId=" + getCourseId())
        .add("courseName=" + getCourseName())
        .add("isActive=" + getIsActive())
        .toString();
  } // endregion toString()
  // endregion Constructor, getters, setters, equals, hashCode, toString
}
