/* (C)2023 */
package com.utopiannerd.techcoaching.dao.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import java.util.Objects;
import java.util.StringJoiner;

@Entity
public class Student {

  @Id private long studentId;
  private long batchId;
  private String fullName;
  private String fullAddress;
  private boolean isActive;

  // region Constructor, getters, setters, equals, hashCode, toString, builder -- generated by BoB
  // the Builder of Beans
  // The code below has been generated by BoB the Builder of Beans based on the class' fields.
  // Everything after this comment will be regenerated if you invoke BoB again.
  // If you don't know who BoB is, you can find him here:
  // https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

  protected Student(
      long studentId, long batchId, String fullName, String fullAddress, boolean isActive) {
    this.studentId = studentId;
    this.batchId = batchId;
    this.fullName = Objects.requireNonNull(fullName);
    this.fullAddress = Objects.requireNonNull(fullAddress);
    this.isActive = isActive;
  }

  public Student() {}

  // region Getters and setters -- generated by BoB the Builder of Beans
  public long getStudentId() {
    return studentId;
  }

  public void setStudentId(long studentId) {
    this.studentId = studentId;
  }

  public long getBatchId() {
    return batchId;
  }

  public void setBatchId(long batchId) {
    this.batchId = batchId;
  }

  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = Objects.requireNonNull(fullName);
  }

  public String getFullAddress() {
    return fullAddress;
  }

  public void setFullAddress(String fullAddress) {
    this.fullAddress = Objects.requireNonNull(fullAddress);
  }

  public boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(boolean isActive) {
    this.isActive = isActive;
  } // endregion Getters and setters

  // region hashCode() and equals() -- generated by BoB the Builder of Beans
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    Student that = (Student) o;

    return Objects.equals(this.getStudentId(), that.getStudentId())
        && Objects.equals(this.getBatchId(), that.getBatchId())
        && Objects.equals(this.getFullName(), that.getFullName())
        && Objects.equals(this.getFullAddress(), that.getFullAddress())
        && Objects.equals(this.getIsActive(), that.getIsActive());
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        getStudentId(), getBatchId(), getFullName(), getFullAddress(), getIsActive());
  } // endregion hashCode() and equals()

  // region toString() -- generated by BoB the Builder of Beans
  @Override
  public String toString() {
    return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
        .add("studentId=" + getStudentId())
        .add("batchId=" + getBatchId())
        .add("fullName=" + getFullName())
        .add("fullAddress=" + getFullAddress())
        .add("isActive=" + getIsActive())
        .toString();
  } // endregion toString()

  // region Builder -- generated by BoB the Builder of Beans
  public static Student.Builder builder() {
    return new Student.Builder();
  }

  public static Student.Builder builder(Student data) {
    return new Student.Builder(data);
  }

  public static final class Builder {

    private long studentId;
    private long batchId;
    private String fullName;
    private String fullAddress;
    private boolean isActive;

    private Builder() {}

    private Builder(Student initialData) {
      this.studentId = initialData.studentId;
      this.batchId = initialData.batchId;
      this.fullName = initialData.fullName;
      this.fullAddress = initialData.fullAddress;
      this.isActive = initialData.isActive;
    }

    public Builder setStudentId(long studentId) {
      this.studentId = studentId;
      return this;
    }

    public Builder setBatchId(long batchId) {
      this.batchId = batchId;
      return this;
    }

    public Builder setFullName(String fullName) {
      this.fullName = fullName;
      return this;
    }

    public Builder setFullAddress(String fullAddress) {
      this.fullAddress = fullAddress;
      return this;
    }

    public Builder setIsActive(boolean isActive) {
      this.isActive = isActive;
      return this;
    }

    public Student build() {
      return new Student(studentId, batchId, fullName, fullAddress, isActive);
    }
  } // endregion Builder
  // endregion Constructor, getters, setters, equals, hashCode, toString, builder
}
